// define the Route
const ROUTES = {
  GUEST_HOME: '/',
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  CONFIRM_EMAIL: '/confirm-email',
  FORGOT_PASSWORD: '/forgot-password',
  RESEND_PASSWORD: '/resend-password',
  SUCCESS_CONFIRM: '/email-success-confirm',
  PROFILE: '/profile',
  CONTACT: '/contact',
  BLOG: '/blog',
  SERVICES: '/services',
  NUTRITION_AND_FITNESS: '/nutrition-and-fitness',
  COMMUNITY: '/community',
  MEMBESHIP_PLANS: '/membership-plans',
  DETAIL_PLAN: '/detail-plan',
  CHECKOUT: '/checkout',
  VNPAY: '/vnpay',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_TRANSACTION: '/admin/transaction',
  ADMIN_MEMBER: '/admin/member',
  ADMIN_MEMBERSHIP_PLAN: '/admin/membership-plans',
  MEMBER_DASHBOARD: '/member',
  MEMBER_TRACKING: '/member/tracking',
  MEMBER_FETALGROWTHCHART: '/member/fetal-growth-chart',
  SCHEDULE: '/schedule',
  NOT_FOUND: '*'
}
export default ROUTES
